```groovy
pipeline {

    agent any

    tools {
        jdk 'JAVA_21'
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Cloning repository from GitHub'

                git branch: 'main',
                    url: 'https://github.com/hemu0119/SDET_Capstone_Project.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Cleaning Project'
                bat 'cd ParaBank && mvn clean'
            }
        }

        stage('Execute Tests') {
            steps {
                echo 'Running Selenium Tests'
                bat 'cd ParaBank && mvn test'
            }
        }
    }

    post {

        always {

            archiveArtifacts artifacts: 'ParaBank/test-output/**/*.*',
                             fingerprint: true

            archiveArtifacts artifacts: 'ParaBank/target/**/*.*',
                             fingerprint: true

            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'ParaBank/test-output',
                reportFiles: 'ExtentReport.html',
                reportName: 'ParaBank Extent Report'
            ])
        }

        success {
            echo 'ParaBank Automation Execution Successful'
        }

        failure {
            echo 'ParaBank Automation Execution Failed'
        }
    }
}
```
